### ISSUE TITLE
Calendar access

### ISSUE THREAD

**Issue by wilme861** [AnonymousController/wstc#3]
Whenever I run the script as the application, I constantly get a pop up saying:

The application would like to access your calendar. This script needs access to your calendars to run.

It provides two options, Don't Allow or OK. When I click OK, the same pop up just pops up again and again and again. After about 15-20 times of it, the script will finally move on to the next step but immediately do the same thing.

I've enable access, I can see it enabled under system settings, privacy, calendar and it's checked to allow access but still have this over and over again no matter what.

Any ideas on what I'm missing?

**Comment by AnonymousController** [comment]
That "would like to access" popup is a system popup. I trigger it by making Calendar execute a dummy command, and then the system catches that and asks if you want to allow access. It sounds to me like the system isn't properly registering your "OK" selection, so the next time there's a Calendar access—and the time after that—and the time after that—it keeps re-asking for your approval, because it doesn't remember that you said "OK" before.

In theory, if you clicked "Don't Allow" then an error would occur the next time the script tried to access Calendar:

<img width="372" alt="Screen shot of error: Not authorized to send events to Apple Calendar" src="https://github.com/AnonymousController/wstc/assets/64904970/788b2b6a-35b7-4f15-9559-aac48e20dab4">

But if my theory is correct and your system isn't remembering anything one way or the other, you would just continue to see the same "would like to access" popup over and over.

Unfortunately I can't reproduce on my end, but I am using an older version of macOS. What version are you using? Apple does like to change the way things work. I'll leave the issue open and see if it's a problem for anyone else.

**Comment by wilme861** [comment]
I'm on Ventura 13.4.1.

I was using the script as an application. I just used it now as a script instead and it works perfectly so no idea what's up with using it as an application.

**Comment by wilme861** [comment]
So got a new Mac and zero issues this time setting it up as an application. Works perfectly.
