### ISSUE TITLE
The script has been recompiled since the last time it was run.

### ISSUE THREAD

**Issue by chdrinkall** [AnonymousController/wstc#5]
<img width="427" alt="Screenshot 2023-10-18 at 10 39 28" src="https://github.com/AnonymousController/wstc/assets/4854286/a1c8dc07-7b3c-44bc-8d14-26c707c82197">

Shows this every time I run it. I have to enter the password every time. Other than that it works perfectly. Thanks!

**Comment by AnonymousController** [comment]
That is strange. You have saved the code on your computer, right? You aren't just copying and pasting the code into a new Script Editor document every single time?

I would try exporting the file as an application and running that. Try checking the "Run-only" option in the export dialog. Also experiment with the Code Sign option, do it both ways and see if that makes a difference. On my computer I selected "Sign to Run Locally."

**Comment by wilme861** [comment]
I have the same issue.

I've saved the script and run that each time. I can't use it as an application without it requesting access to my calendar over and over and over, which I don't have a problem with when running as a script. I get that recompile message though each time I run the script.

**Comment by AnonymousController** [comment]
So the password entry does work the second time, just not the first? That does point to an issue with the internal password the script creates for itself, because the website entry is exactly the same.

Just to be sure, can you try setting `property pw` on line 136 to something static? So change `do shell script "openssl rand -base64 30"` to a set string like `"password"` (with the quotes). The first time you run the new code you should see the same "recompiled" error, but the second time it should work. If there's still a problem the second time you run the code that would point to something wrong with the decryption process.

**Comment by wilme861** [comment]
> So the password entry does work the second time, just not the first? That does point to an issue with the internal password the script creates for itself, because the website entry is exactly the same.
> 
> Just to be sure, can you try setting `property pw` on line 136 to something static? So change `do shell script "openssl rand -base64 30"` to a set string like `"password"` (with the quotes). The first time you run the new code you should see the same "recompiled" error, but the second time it should work. If there's still a problem the second time you run the code that would point to something wrong with the decryption process.

Changing it to "password" worked. No compile error (except the first one).

**Comment by AnonymousController** [comment]
That means one of three things. The least likely possibility is that something is going wrong with generating the password itself. That doesn't make a lot of sense because when the script encounters the error and asks you to re-enter your MyAccess password, it immediately encrypts what you enter using the password and then decrypts it again in order to put it into the webpage. The more likely possibility is that somehow the script is in fact being re-compiled each time you run it, which should not be the case. And the third possibility is that Apple made a change in MacOS and now properties like this are re-run every time the script is run, even if it hasn't been recompiled.

Just for fun, you could try restoring `property pw : do shell script "openssl rand -base64 30"` and then putting a quick `display dialog pw` in the main function's try block, like at line 159. See if that randomly generated password stays the same each time you run the script or if it changes, or if there truly is some problem and it throws an error even before displaying the password.

But the permanent fix for you is to keep pw static, the way you have it now. Whatever random text you like will work fine. This means someone with access to your computer will be able to decrypt your saved MyAccess password but the new default password is already printed on your PIV so that doesn't matter very much.
